variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo

cache:
  paths:
    - .cargo
    - target

stages:
  - pre-build
  - build

clippy_and_rustfmt:
  stage: pre-build
  image: guangie88/rustfmt-clippy:stable
  script:
   - cargo clippy --verbose
   - cargo fmt -- --check
  allow_failure: true

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose
    - cargo test --verbose
  needs: []

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose
    - cargo test --verbose
  allow_failure: true
  needs: []
