[package]
name = "mudibot"
version = "0.8.0"
authors = ["Thomas Donovan <tdonovan@codengineer.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.8"
chrono = "0.4"
sysinfo = "0.13"