[default]
ignore-tests = true
out = ["Html"]
output-dir = "target/tarpaulin"
# Still won't exclude with ignore-tests
# For some reasons it includes the struct IdentWrapper in logger
exclude-files = ["test_doubles.rs", "logger.rs"]